### ISSUE TITLE
Initializer parameter type hint: Iterator or Iterable?

### ISSUE THREAD

**Issue by chludwig-haufe** [bustawin/ordered-set-37#1]
Hi,

I am wondering about the signature of `OrderedSet.__init__(self, iterable: t.Optional[t.Iterator[T]] = None)`. Why did you declare `iterable` to be an _Iterator[T]_ (or None) instead of an _Iterable[T]_? `dict.from_keys()` (which you call in your implementation) accepts any `Iterable[T]`.

Not only does the parameter name suggest this was an oversight, but  `collections.abc.Iterator` also [inherits](https://docs.python.org/3/library/collections.abc.html#collections-abstract-base-classes) from `collections.abc.Iterable`; the former is therefore the more specialized type. 

The collection classes are iterables but _not_ iterator instances. In fact, initializing `OrderedSet` from a list, set, or even another `OrderedSet` instance works fine but makes [mypy](https://mypy.readthedocs.io/en/latest/index.html) complain:
```
$ mypy ~/.pyenv/versions/ong-mono/lib/python3.8/site-packages/ordered_set_37/__init__.py ~/Library/Application\ Support/Jetbrains/PyCharm2020.2/scratches/scratch.py
/Users/ludwigc/Library/Application Support/Jetbrains/PyCharm2020.2/scratches/scratch.py:3: error: Argument 1 to "OrderedSet" has incompatible type "List[str]"; expected "Optional[Iterator[str]]"
/Users/ludwigc/Library/Application Support/Jetbrains/PyCharm2020.2/scratches/scratch.py:5: error: Argument 1 to "OrderedSet" has incompatible type "OrderedSet[str]"; expected "Optional[Iterator[<nothing>]]"
Found 2 errors in 1 file (checked 2 source files)
```

**Comment by bustawin** [comment]
You are right. Will push a fix later.

**Comment by chludwig-haufe** [comment]
While you are at it: Could you release the package as a non-beta version? I don't see many bug reports coming in that would require another beta period, do you? :-)

**Comment by bustawin** [comment]
I was looking for an excuse for that ;-)
