### ISSUE TITLE
discard(elem) raises KeyError on missing element

### ISSUE THREAD

**Issue by chludwig-haufe** [bustawin/ordered-set-37#2]
Hi,

according to the [Python documentation of Set Types](https://docs.python.org/3/library/stdtypes.html#set-types-set-frozenset), the difference between `remove(elem)` and `discard(elem)` is that the former raises a `KeyError` if `elem`is not a member of the set whereas the latter is a no-op in this case.

Unfortunately, in ordered-set-37 version 1.0, both `OrderedSet.remove(elem)` and `OrderedSet.discard(elem)` raise a `KeyError` if the argument is not in the set. Test case:
``` python
import pytest
from ordered_set_37 import OrderedSet


def test_discard_deletes_existing_element():
    x = OrderedSet([1, 2, -1])
    x.discard(2)
    assert list(x) == [1, -1]

def test_discard_ignores_missing_element():
    x = OrderedSet([1, 2, -1])
    x.discard(3)
    assert list(x) == [1, 2, -1]

def test_remove_deletes_existing_element():
    x = OrderedSet([1, 2, -1])
    x.remove(2)
    assert list(x) == [1, -1]

def test_remove_raises_key_error_on_missing_element():
    x = OrderedSet([1, 2, -1])
    with pytest.raises(KeyError):
        x.remove(3)

    # x is not modified
    assert list(x) == [1, 2, -1]
```

Abbreviated test output:
```
================ FAILURES =================
____ test_discard_ignores_missing_element____

    def test_discard_ignores_missing_element():
        x = OrderedSet([1, 2, -1])
>       x.discard(3)

scratch_1.py:13:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <OrderedSet {1, 2, -1}>, x = 3

    def discard(self, x: T) -> None:
>       self._d.pop(x)
E       KeyError: 3

../../.pyenv/versions/3.8.1/envs/ong-mono/lib/python3.8/site-packages/ordered_set_37/__init__.py:20: KeyError
=========================================
```

Proposed fix: Add an (ignored) default argument to the call of `dict.pop(x)` in [line 20 of `ordered_set_37.__init__.py`](https://github.com/bustawin/ordered-set-37/blob/2413c0d1cb8056af6402ce2433a599c582ce5cec/ordered_set_37/__init__.py#L20), e.g.:
```python
    def discard(self, x: T) -> None:
        self._d.pop(x, None)
```

**Comment by bustawin** [comment]
Better late than ever..! It's fixed on pypi. Just `pip install -U ordered-set-37`. Thank you!
