### ISSUE TITLE
Missing `update` method

### ISSUE THREAD

**Issue by Changaco** [bustawin/ordered-set-37#4]
The built-in `set` class has an `update` method, but the `OrderedSet` class doesn't.

**Comment by bustawin** [comment]
It's a design choice by the python creators; checkout [this bug and its answers](https://bugs.python.org/issue22089). Tldr, you should use the operator `x |= set1 | set2`.

**Comment by Changaco** [comment]
Thanks for the link, but I don't think Guido's decision not to add the `update` method to the `MutableSet` ABC justifies not adding that method to the `OrderedSet` class.
